apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  CI_BUILD: {{ .Values.data.CI_BUILD }}
  FQDN: {{ .Values.data.FQDN }}

  LLM: {{ .Values.data.LLM }}
  OLLAMA_HOST: {{ .Values.data.OLLAMA_HOST }}
  AZURE_OPENAI_API_KEY: {{ .Values.data.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.data.AZURE_OPENAI_ENDPOINT }}
  AZURE_OPENAI_API_VERSION: {{ .Values.data.AZURE_OPENAI_API_VERSION }}
  HUGGINGFACE_TOKEN: {{ .Values.data.HUGGINGFACE_TOKEN }}

  MSAL_CLIENT_ID: {{ .Values.data.MSAL_CLIENT_ID }}
  MSAL_AUTHORITY: {{ .Values.data.MSAL_AUTHORITY }}
  STREAMLIT_CHAT_APP_PORT: '{{ .Values.port }}'

  DATABASE_URL: '{{ .Values.data.DATABASE_URL }}'
  CHROMADB_HOST: {{ .Values.data.CHROMADB_HOST }}
  CHROMADB_PORT: '{{ .Values.data.CHROMADB_PORT }}'
  CHROMA_CLIENT_AUTH_TOKEN: {{ .Values.data.CHROMA_CLIENT_AUTH_TOKEN }}
  S3_HOST: {{ .Values.data.S3_HOST }}
  S3_BUCKET: {{ .Values.data.S3_BUCKET }}
  S3_ACCESS_KEY: {{ .Values.data.S3_ACCESS_KEY }}
  S3_SECRET_KEY: {{ .Values.data.S3_SECRET_KEY }}
  ROSTER_FILE: {{ .Values.data.ROSTER_FILE }}
  LOCAL_FILE_CACHE: {{ .Values.data.LOCAL_FILE_CACHE }}
  ADMIN_USERS: {{ .Values.data.ADMIN_USERS }}
  PROMPTS_FILE: {{ .Values.data.PROMPTS_FILE }}
  CONFIG_FILE: {{ .Values.data.CONFIG_FILE }}
  PROMPTS_FILE_FALLBACK: {{ .Values.data.PROMPTS_FILE_FALLBACK }}
  CONFIG_FILE_FALLBACK: {{ .Values.data.CONFIG_FILE_FALLBACK }}

  ROSTER_EXCEPTION_USERS: {{ .Values.data.ROSTER_EXCEPTION_USERS }}
