apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  rules:
  - host: {{ .Values.data.FQDN }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-app-service
            port:
              number: {{ .Values.port }}
  tls:
    - hosts:
        - {{ .Values.data.FQDN }}
      secretName: {{ .Release.Name }}-tls
