name: Build and Publish Docker Image

on:
  push:
    branches:
      - main


jobs:
    publish_to_ghcr:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout this repo
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Build and push
          run: |
            docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest --tag ghcr.io/${{ github.repository }}:${{github.sha}}
            docker push ghcr.io/${{ github.repository }}:${{github.sha}}
            docker push ghcr.io/${{ github.repository }}:latest

        - name: Checkout the deploy repo
          uses: actions/checkout@v4
          with:
            repository: 'cent-ischool/ist256-chatapp-deploy'
            path: 'chatapp-deploy'
            github-server-url: 'https://github.com'
            token: ${{ secrets.PAT }}

        - name: Write the SHA to the deploy repo overwrite the values.yaml
          run: |
            echo ${{ github.sha }} > chatapp-deploy/SHA
            sed -i 's/\(CI_BUILD:\).*/\1 ${{ github.sha }}/' chatapp-deploy/chatapp/values.yaml
            
        - name: git commit and push trigger CD 
          run: |
            cd chatapp-deploy
            git config --global user.name "Github Actions Ci"
            git config --global user.email "github-actions-ci@cent-su.org"
            git add SHA
            git commit -a -m "${{ github.sha }}"
            git push